### ISSUE TITLE
`\=` for Semigroup and an Ideal crashes if given infinite inputs

### ISSUE THREAD

**Issue by markuspf** [gap-packages/Semigroups#508] opened 2018-09-06 09:08 UTC
```
gap> M := Magma(0,1,2);;
gap> SetIsFinite(M, false);
gap> J := MagmaIdealByGenerators(M,[2]);;
gap> SetIsFinite(J, false);
gap> M = J;
```

makes GAP run out of memory, because the method executed (`=` for an ideal with generators and a semigroup with generators https://github.com/gap-packages/Semigroups/blob/f431ea45eeefcf7dd5495b18084f3cef3b6281d7/gap/ideals/ideals.gi#L164) tries to enumerate the ideal for a membership test.

Either `Semigroups` assumes these objects are finite (in which case the filters should reflect this, but of course could still run out of memory...), or there is an intrinsic reason why there are always membership tests for these objects in semigroups (in which case i would like to know what they are).

I should note that the test in gap (`tst/testinstall/domain.tst`) that exposes this behaviour is a bit of a hack to create domains that are infinite and are supposed to be caught to be incomparable.

**Comment by james-d-mitchell** [comment] 2018-09-06 14:27
Thanks for the report. It looks to me that probably the filters for the `\=` method for an ideal and generators are perhaps too permissive. 

On the other hand, how does GAP know that they are or are not equal @markuspf ?

**Comment by wilfwilson** [comment] 2018-09-06 14:29
In GAP, without Semigroups, you get:
```
gap> M := Magma(0,1,2);;
gap> SetIsFinite(M, false);
gap> J := MagmaIdealByGenerators(M,[2]);;
gap> SetIsFinite(J, false);
gap> M = J;
Error, no method found for comparing two infinite domains
```

**Comment by wilfwilson** [comment] 2018-09-07 09:12
As the Travis tests for #510 show, this is now the only thing stopping our Travis tests from passing in the master branch.

**Comment by fingolfin** [comment] 2018-09-10 14:59
AFAIK this is a blocker for GAP 4.10. So if it helps, we could simply disable this test in GAP, at least for now (of course it'd still be nice if for semigroups which are known to be infinite, tests which may not terminate were linited... but at least from my POV that's not particularly important; so let's be pragmatic

**Comment by alex-konovalov** [comment] 2018-09-10 15:27
I am for this. Then this plus https://github.com/gap-system/gap/pull/2796 plus new release of Semigroups will  make us ready for branching off stable-4.10.

**Comment by alex-konovalov** [comment] 2018-09-10 15:35
@wilfwilson will you be able to submit another PR to disable this test in GAP then, please?

**Comment by wilfwilson** [comment] 2018-09-10 15:38
I believe that the offending method that Markus references above does implicitly require that the arguments be finite. In the case that `S` is not equal to the `Parent` of `I`, and we don't know the generators of `I` as a semigroup, then the method uses the following logic:

An ideal `I` is equal to a semigroup `S` if and only if `S <= I` and `Size(S) = Size(I)`.

This is fine for finite things. This statement does not hold in the infinite case (in particular consider when `S` is an infinite proper subsemigroup of `I`).

I propose adding `IsFinite` to the filters of this method. I'll make a PR doing this.

**Comment by wilfwilson** [comment] 2018-09-10 15:51
Similar problems might exist at other places in `gap/attributes/ideals.gi`; I will try to have a look at the GAP Days next week when I will have time to do so.

**Comment by fingolfin** [comment] 2018-09-10 16:03
Of course adding those `IsFinite` filters (if they make sense, and don't cause further problems) would be best. But since that is nontrivial and has the risk of causing its own regressions, and for the sake of getting GAP 4.10 out of the door, I'd still disable the problematic test in GAP for now first; we can evaluate re-enabling it if and when that seems possible due to changes made on the semigroups side (and/or in GAP, of course, if that turns out to be necessary).

**Comment by wilfwilson** [comment] 2018-09-10 17:29
See https://github.com/gap-system/gap/pull/2797.

**Comment by wilfwilson** [comment] 2018-09-10 20:31
This is resolved by https://github.com/gap-packages/Semigroups/pull/513. I also made a PR to GAP at https://github.com/gap-system/gap/pull/2797 which will also stop this being a problem between now and the next release of Semigroups.

**Closed by wilfwilson** 2018-09-10 20:31 UTC
Labels: 3.0, bug, help wanted, minor
