### ISSUE TITLE
HClasses of an LClass of a semigroup from smallsemi package

### ISSUE THREAD

**Issue by ChristopherRussell** [gap-packages/Semigroups#413] opened 2017-11-13 10:27 UTC
I get the following issue with the examples of semigroups from the smallsemi package which I have tried.

```
gap> SmallSemigroup(3, 1);
<small semigroup of size 3>
gap> GreensLClasses(last);
[ <Green's L-class: s1>, <Green's L-class: s2>, <Green's L-class: s3> ]
gap> GreensHClasses(last[1]);
Error, recursion depth trap (5000) in
  return GreensHClasses( CanonicalGreensClass( x ) ); at /Users/crussell/gap/lib/semirel.gi:724 called from
GreensHClasses( CanonicalGreensClass( x ) ) at /Users/crussell/gap/lib/semirel.gi:724 called from
GreensHClasses( CanonicalGreensClass( x ) ) at /Users/crussell/gap/lib/semirel.gi:724 called from
GreensHClasses( CanonicalGreensClass( x ) ) at /Users/crussell/gap/lib/semirel.gi:724 called from
GreensHClasses( CanonicalGreensClass( x ) ) at /Users/crussell/gap/lib/semirel.gi:724 called from
GreensHClasses( CanonicalGreensClass( x ) ) at /Users/crussell/gap/lib/semirel.gi:724 called from
...  at *stdin*:35
you may 'return;'
```

**Comment by james-d-mitchell** [comment] 2017-11-13 17:40
This is not a bug in the Semigroups package, I remember that this issue was reported in the main GAP repo some years ago.

**Comment by wilfwilson** [comment] 2018-09-19 09:42
Yeah this is not the fault of the Semigroups package...

...but I'm not sure if this counts as a bug in GAP per se: GAP only documents `GreensXClasses` as an attribute for a semigroup:
```
51.8-9 GreensRClasses

  ‣ GreensRClasses( semigroup ) ──────────────────────────────────── attribute
  ‣ GreensLClasses( semigroup ) ──────────────────────────────────── attribute
  ‣ GreensJClasses( semigroup ) ──────────────────────────────────── attribute
  ‣ GreensDClasses( semigroup ) ──────────────────────────────────── attribute
  ‣ GreensHClasses( semigroup ) ──────────────────────────────────── attribute

  return  the  R,  L,  J,  H, or D Green's classes, respectively for semigroup
  semigroup. EquivalenceClasses (33.7-3) for a Green's relation lead to one of
  these functions.
```
That said, there exist some non-functional methods that @ChristopherRussell has found above. I'll have a go at sorting this out.

**Comment by james-d-mitchell** [comment] 2018-09-19 09:44
So, I'm embarrassed to admit that I wrote much of the Green's class stuff in the GAP library. The best way to improve that, would be delete it completely!

**Comment by wilfwilson** [comment] 2018-09-19 10:00
Even if so, I don't think that's imminently on the cards. I think I can fix this thing easily, so I'll do it.

**Comment by james-d-mitchell** [comment] 2018-09-19 10:30
Yes, of course, by all means 👍

**Comment by wilfwilson** [comment] 2018-09-19 12:27
Feel free to review and merge that PR @james-d-mitchell 😉 https://github.com/gap-system/gap/pull/2830

**Comment by james-d-mitchell** [comment] 2018-09-19 12:52
I've reviewed it, but I revoked my write access to the main GAP repo, so someone else will have to merge it I'm afraid...

**Comment by wilfwilson** [comment] 2018-09-19 12:54
Thank you!

**Comment by wilfwilson** [comment] 2018-09-20 14:41
This specific problem is now fixed in GAP master branch.

**Closed by wilfwilson** 2018-09-20 14:41 UTC
Labels: bug, invalid
