### ISSUE TITLE
EndomorphismMonoid on a digraph and list of colours gives non-endomorphisms

### ISSUE THREAD

**Issue by flsmith** [gap-packages/Semigroups#183] opened 2016-06-07 22:50 UTC
EndomorphismMonoid seems to be giving results that aren't endomorphisms. In the following example, (7,16) -> (7,13) which is not an edge.

```
gap> digraph:=[ [ 7, 13 ], [ 8, 14 ], [ 9, 15 ], [ 10, 16 ], [ 11, 17 ], [ 12, 18 ], 
>   [ 1, 19, 16 ], [ 2, 20 ], [ 3, 21 ], [ 4, 22 ], [ 5, 23 ], [ 6, 24 ], 
>   [ 1, 25 ], [ 2, 26 ], [ 3, 27 ], [ 4, 28, 7 ], [ 5, 29 ], [ 6, 30 ], [ 7 ], 
>   [ 8, 29 ], [ 9, 30 ], [ 10 ], [ 11 ], [ 12 ], [ 13 ], [ 14 ], [ 15 ], 
>   [ 16 ], [ 17, 20 ], [ 18, 21 ] ];;
gap> colors:=[ 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 
>   6, 6, 6, 6, 6 ];;
gap> EndM:=Set(AsList(EndomorphismMonoid(Digraph(digraph),colors)));;
gap> T:=EndM[1];
Transformation( [ 1, 2, 2, 1, 5, 5, 7, 8, 8, 7, 11, 11, 13, 14, 14, 13, 17,
  17, 19, 20, 19, 22, 23, 23, 25, 26, 26, 28, 29, 29 ] )
gap> 16 in digraph[7];
true
gap> 16^T in digraph[7^T];
false

```

**Comment by james-d-mitchell** [comment] 2016-06-08 10:11
This was caused by incorrectly using the library method for `IsomorphismTransformationMonoid` of a perm group in the `EndomorphismMonoid` code. I decided to change the library method to something more sensible. This is in the `fix-semi-iso` branch of my fork of GAP.

**Comment by james-d-mitchell** [comment] 2016-06-08 10:11
I'll leave this open until all the travis test have finished running.

**Comment by james-d-mitchell** [comment] 2016-12-22 20:25
I'm going to close this issue, since it has been resolved.

**Closed by james-d-mitchell** 2016-12-22 20:25 UTC
