### ISSUE TITLE
Failures in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Semigroups#632] opened 2019-12-15 10:11 UTC
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/624910497 shows this:
```
testing: /home/gap/inst/gap-master/pkg/semigroups-3.2.0/tst/standard/attr.tst
######## > Diff in:
/home/gap/inst/gap-master/pkg/semigroups-3.2.0/tst/standard/attr.tst:1210
# Input is:
S := Monoid(Matrix(GF(2 ^ 2),
[[Z(2 ^ 2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2)],
 [Z(2 ^ 2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2)],
 [0 * Z(2), Z(2) ^ 0, 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2)],
 [0 * Z(2), 0 * Z(2), Z(2) ^ 0, 0 * Z(2), 0 * Z(2), 0 * Z(2)],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), Z(2) ^ 0, 0 * Z(2), 0 * Z(2)],
 [0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2), 0 * Z(2)]]));;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 2nd choice method found for `OneMutable' on 1 arguments
########
```

**Comment by wilfwilson** [comment] 2019-12-15 10:57
Thanks. Before looking into this further, I’ll note that Semigroups 3.2.1 is the most recent version (not 3.2.0, as you are testing there), so it’s possible that the problem is fixed already. If the problems still exist with Semigroups 3.2.1, then we’ll definitely look into it properly 🙂

**Comment by alex-konovalov** [comment] 2019-12-15 11:45
Ok - a new test is now running at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/builds/625265651, it has Semigroups 3.2.1. Let's watch it.

**Comment by alex-konovalov** [comment] 2019-12-15 14:14
@wilfwilson ok now - sorry for the false alarm: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/625265734

**Comment by alex-konovalov** [comment] 2019-12-20 18:41
Still something is wrong here:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11/jobs/627234005
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/627054183

**Comment by james-d-mitchell** [comment] 2019-12-23 09:43
Hmm interesting, I will try to investigate this later today.

**Comment by james-d-mitchell** [comment] 2019-12-23 14:58
@alex-konovalov I think I've fixed one of the issues, I'm not sure about the other one. Once PR #633 is merged is there a way to reproduce/rerun the tests that failed?

**Comment by alex-konovalov** [comment] 2019-12-23 15:59
Now passes - let's observe it a bit more: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging

**Comment by james-d-mitchell** [comment] 2019-12-23 16:08
Seems like everything passes ok for Semigroups (although everything else seems to fail in your last link!).

**Comment by alex-konovalov** [comment] 2019-12-23 19:14
Yes, because it's a staging test - everything that is known to pass moves to https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master

**Comment by james-d-mitchell** [comment] 2019-12-25 18:50
Só if I make release of Semigroups this will be resolved?

**Comment by alex-konovalov** [comment] 2019-12-28 13:26
It's already passes for this Semigroups release @james-d-mitchell - you don't have to do anything.

**Closed** 2019-12-29 09:44 UTC
